version: '3'
services:
  airflow:
    image: apache/airflow:2.7.1
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
    volumes:
      - ./airflow:/opt/airflow
      - ./dbt:/opt/dbt
    ports:
      - "8080:8080"
